# Generated by Django 3.1.2 on 2020-11-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20201124_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto1',
            fields=[
                ('id', models.IntegerField(help_text='Código del producto', primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=200)),
                ('prec', models.IntegerField(help_text='Precio producto')),
                ('cant', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='images_2/')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
